[package]
name = "personal_search"
version = "0.1.0"
authors = ["becker <github@deathbyescalator.com>"]
edition = "2018"

[features]
firefox_sync = [ "rusqlite", "glob", "dirs" ]

[dependencies]
tantivy = "*"
reqwest = { version = "*", features = ["blocking"] }
select = "*"
tempfile = "*"
chrono = "*"
lazy_static = "*"
toml = "*"
structopt = "*"

dirs = { version = "*", optional = true }
rusqlite = { version = "*", optional = true }
glob = { version = "*", optional = true }
probabilistic-collections = { version = "*", features = ["serde"] }
triple_accel =  { version = "*" }
md5 =  { version = "*"}
rust-bert ={ version = "*" }

[[bin]]
name = "firefox_sync"
path = "src/firefox_sync/main.rs"
features = ["firefox_sync"]
